# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d09d46021eb585339618f0ef60d90a9d0f0327b7774fe75d60cf2ee576f19bd7db28d5b06c4b3c19b270790262893e4d890803184306e718cb20d668cabc24e

test:
  secret_key_base: c99b3ad7f3710c9cacb48ef5039d33f8253804e51695c1541c303eaec8303143ea1bc5ad0e221ccc1b8ceaa79eaf6241e6d2646f1846cdca2b00b650c942d644

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
